// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proxy.proto
#ifndef GRPC_proxy_2eproto__INCLUDED
#define GRPC_proxy_2eproto__INCLUDED

#include "proxy.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace goproxy {

class NodeService final {
 public:
  static constexpr char const* service_full_name() {
    return "goproxy.NodeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AddNode(::grpc::ClientContext* context, const ::goproxy::Url& request, ::goproxy::AddedNodesCount* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::AddedNodesCount>> AsyncAddNode(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::AddedNodesCount>>(AsyncAddNodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::AddedNodesCount>> PrepareAsyncAddNode(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::AddedNodesCount>>(PrepareAsyncAddNodeRaw(context, request, cq));
    }
    virtual ::grpc::Status AddSubscription(::grpc::ClientContext* context, const ::goproxy::Url& request, ::goproxy::SubscriptionId* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::SubscriptionId>> AsyncAddSubscription(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::SubscriptionId>>(AsyncAddSubscriptionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::SubscriptionId>> PrepareAsyncAddSubscription(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::SubscriptionId>>(PrepareAsyncAddSubscriptionRaw(context, request, cq));
    }
    virtual ::grpc::Status FetchSubscriptionNodes(::grpc::ClientContext* context, const ::goproxy::SubscriptionId& request, ::goproxy::AddedNodesCount* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::AddedNodesCount>> AsyncFetchSubscriptionNodes(::grpc::ClientContext* context, const ::goproxy::SubscriptionId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::AddedNodesCount>>(AsyncFetchSubscriptionNodesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::AddedNodesCount>> PrepareAsyncFetchSubscriptionNodes(::grpc::ClientContext* context, const ::goproxy::SubscriptionId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::AddedNodesCount>>(PrepareAsyncFetchSubscriptionNodesRaw(context, request, cq));
    }
    virtual ::grpc::Status GetNodes(::grpc::ClientContext* context, const ::goproxy::Null& request, ::goproxy::Nodes* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::Nodes>> AsyncGetNodes(::grpc::ClientContext* context, const ::goproxy::Null& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::Nodes>>(AsyncGetNodesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::Nodes>> PrepareAsyncGetNodes(::grpc::ClientContext* context, const ::goproxy::Null& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::Nodes>>(PrepareAsyncGetNodesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AddNode(::grpc::ClientContext* context, const ::goproxy::Url* request, ::goproxy::AddedNodesCount* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddNode(::grpc::ClientContext* context, const ::goproxy::Url* request, ::goproxy::AddedNodesCount* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void AddSubscription(::grpc::ClientContext* context, const ::goproxy::Url* request, ::goproxy::SubscriptionId* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddSubscription(::grpc::ClientContext* context, const ::goproxy::Url* request, ::goproxy::SubscriptionId* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void FetchSubscriptionNodes(::grpc::ClientContext* context, const ::goproxy::SubscriptionId* request, ::goproxy::AddedNodesCount* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FetchSubscriptionNodes(::grpc::ClientContext* context, const ::goproxy::SubscriptionId* request, ::goproxy::AddedNodesCount* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetNodes(::grpc::ClientContext* context, const ::goproxy::Null* request, ::goproxy::Nodes* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetNodes(::grpc::ClientContext* context, const ::goproxy::Null* request, ::goproxy::Nodes* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::AddedNodesCount>* AsyncAddNodeRaw(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::AddedNodesCount>* PrepareAsyncAddNodeRaw(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::SubscriptionId>* AsyncAddSubscriptionRaw(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::SubscriptionId>* PrepareAsyncAddSubscriptionRaw(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::AddedNodesCount>* AsyncFetchSubscriptionNodesRaw(::grpc::ClientContext* context, const ::goproxy::SubscriptionId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::AddedNodesCount>* PrepareAsyncFetchSubscriptionNodesRaw(::grpc::ClientContext* context, const ::goproxy::SubscriptionId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::Nodes>* AsyncGetNodesRaw(::grpc::ClientContext* context, const ::goproxy::Null& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::goproxy::Nodes>* PrepareAsyncGetNodesRaw(::grpc::ClientContext* context, const ::goproxy::Null& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AddNode(::grpc::ClientContext* context, const ::goproxy::Url& request, ::goproxy::AddedNodesCount* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>> AsyncAddNode(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>>(AsyncAddNodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>> PrepareAsyncAddNode(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>>(PrepareAsyncAddNodeRaw(context, request, cq));
    }
    ::grpc::Status AddSubscription(::grpc::ClientContext* context, const ::goproxy::Url& request, ::goproxy::SubscriptionId* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::SubscriptionId>> AsyncAddSubscription(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::SubscriptionId>>(AsyncAddSubscriptionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::SubscriptionId>> PrepareAsyncAddSubscription(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::SubscriptionId>>(PrepareAsyncAddSubscriptionRaw(context, request, cq));
    }
    ::grpc::Status FetchSubscriptionNodes(::grpc::ClientContext* context, const ::goproxy::SubscriptionId& request, ::goproxy::AddedNodesCount* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>> AsyncFetchSubscriptionNodes(::grpc::ClientContext* context, const ::goproxy::SubscriptionId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>>(AsyncFetchSubscriptionNodesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>> PrepareAsyncFetchSubscriptionNodes(::grpc::ClientContext* context, const ::goproxy::SubscriptionId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>>(PrepareAsyncFetchSubscriptionNodesRaw(context, request, cq));
    }
    ::grpc::Status GetNodes(::grpc::ClientContext* context, const ::goproxy::Null& request, ::goproxy::Nodes* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::Nodes>> AsyncGetNodes(::grpc::ClientContext* context, const ::goproxy::Null& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::Nodes>>(AsyncGetNodesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::Nodes>> PrepareAsyncGetNodes(::grpc::ClientContext* context, const ::goproxy::Null& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::goproxy::Nodes>>(PrepareAsyncGetNodesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AddNode(::grpc::ClientContext* context, const ::goproxy::Url* request, ::goproxy::AddedNodesCount* response, std::function<void(::grpc::Status)>) override;
      void AddNode(::grpc::ClientContext* context, const ::goproxy::Url* request, ::goproxy::AddedNodesCount* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AddSubscription(::grpc::ClientContext* context, const ::goproxy::Url* request, ::goproxy::SubscriptionId* response, std::function<void(::grpc::Status)>) override;
      void AddSubscription(::grpc::ClientContext* context, const ::goproxy::Url* request, ::goproxy::SubscriptionId* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FetchSubscriptionNodes(::grpc::ClientContext* context, const ::goproxy::SubscriptionId* request, ::goproxy::AddedNodesCount* response, std::function<void(::grpc::Status)>) override;
      void FetchSubscriptionNodes(::grpc::ClientContext* context, const ::goproxy::SubscriptionId* request, ::goproxy::AddedNodesCount* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetNodes(::grpc::ClientContext* context, const ::goproxy::Null* request, ::goproxy::Nodes* response, std::function<void(::grpc::Status)>) override;
      void GetNodes(::grpc::ClientContext* context, const ::goproxy::Null* request, ::goproxy::Nodes* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>* AsyncAddNodeRaw(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>* PrepareAsyncAddNodeRaw(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::goproxy::SubscriptionId>* AsyncAddSubscriptionRaw(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::goproxy::SubscriptionId>* PrepareAsyncAddSubscriptionRaw(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>* AsyncFetchSubscriptionNodesRaw(::grpc::ClientContext* context, const ::goproxy::SubscriptionId& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>* PrepareAsyncFetchSubscriptionNodesRaw(::grpc::ClientContext* context, const ::goproxy::SubscriptionId& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::goproxy::Nodes>* AsyncGetNodesRaw(::grpc::ClientContext* context, const ::goproxy::Null& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::goproxy::Nodes>* PrepareAsyncGetNodesRaw(::grpc::ClientContext* context, const ::goproxy::Null& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AddNode_;
    const ::grpc::internal::RpcMethod rpcmethod_AddSubscription_;
    const ::grpc::internal::RpcMethod rpcmethod_FetchSubscriptionNodes_;
    const ::grpc::internal::RpcMethod rpcmethod_GetNodes_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AddNode(::grpc::ServerContext* context, const ::goproxy::Url* request, ::goproxy::AddedNodesCount* response);
    virtual ::grpc::Status AddSubscription(::grpc::ServerContext* context, const ::goproxy::Url* request, ::goproxy::SubscriptionId* response);
    virtual ::grpc::Status FetchSubscriptionNodes(::grpc::ServerContext* context, const ::goproxy::SubscriptionId* request, ::goproxy::AddedNodesCount* response);
    virtual ::grpc::Status GetNodes(::grpc::ServerContext* context, const ::goproxy::Null* request, ::goproxy::Nodes* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AddNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddNode() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AddNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddNode(::grpc::ServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::AddedNodesCount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddNode(::grpc::ServerContext* context, ::goproxy::Url* request, ::grpc::ServerAsyncResponseWriter< ::goproxy::AddedNodesCount>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AddSubscription : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddSubscription() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AddSubscription() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddSubscription(::grpc::ServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::SubscriptionId* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddSubscription(::grpc::ServerContext* context, ::goproxy::Url* request, ::grpc::ServerAsyncResponseWriter< ::goproxy::SubscriptionId>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FetchSubscriptionNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FetchSubscriptionNodes() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_FetchSubscriptionNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchSubscriptionNodes(::grpc::ServerContext* /*context*/, const ::goproxy::SubscriptionId* /*request*/, ::goproxy::AddedNodesCount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchSubscriptionNodes(::grpc::ServerContext* context, ::goproxy::SubscriptionId* request, ::grpc::ServerAsyncResponseWriter< ::goproxy::AddedNodesCount>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetNodes() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::goproxy::Null* /*request*/, ::goproxy::Nodes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNodes(::grpc::ServerContext* context, ::goproxy::Null* request, ::grpc::ServerAsyncResponseWriter< ::goproxy::Nodes>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AddNode<WithAsyncMethod_AddSubscription<WithAsyncMethod_FetchSubscriptionNodes<WithAsyncMethod_GetNodes<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AddNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddNode() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::goproxy::Url, ::goproxy::AddedNodesCount>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::goproxy::Url* request, ::goproxy::AddedNodesCount* response) { return this->AddNode(context, request, response); }));}
    void SetMessageAllocatorFor_AddNode(
        ::grpc::MessageAllocator< ::goproxy::Url, ::goproxy::AddedNodesCount>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::goproxy::Url, ::goproxy::AddedNodesCount>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddNode(::grpc::ServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::AddedNodesCount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddNode(
      ::grpc::CallbackServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::AddedNodesCount* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AddSubscription : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddSubscription() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::goproxy::Url, ::goproxy::SubscriptionId>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::goproxy::Url* request, ::goproxy::SubscriptionId* response) { return this->AddSubscription(context, request, response); }));}
    void SetMessageAllocatorFor_AddSubscription(
        ::grpc::MessageAllocator< ::goproxy::Url, ::goproxy::SubscriptionId>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::goproxy::Url, ::goproxy::SubscriptionId>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddSubscription() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddSubscription(::grpc::ServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::SubscriptionId* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddSubscription(
      ::grpc::CallbackServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::SubscriptionId* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FetchSubscriptionNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FetchSubscriptionNodes() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::goproxy::SubscriptionId, ::goproxy::AddedNodesCount>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::goproxy::SubscriptionId* request, ::goproxy::AddedNodesCount* response) { return this->FetchSubscriptionNodes(context, request, response); }));}
    void SetMessageAllocatorFor_FetchSubscriptionNodes(
        ::grpc::MessageAllocator< ::goproxy::SubscriptionId, ::goproxy::AddedNodesCount>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::goproxy::SubscriptionId, ::goproxy::AddedNodesCount>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FetchSubscriptionNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchSubscriptionNodes(::grpc::ServerContext* /*context*/, const ::goproxy::SubscriptionId* /*request*/, ::goproxy::AddedNodesCount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FetchSubscriptionNodes(
      ::grpc::CallbackServerContext* /*context*/, const ::goproxy::SubscriptionId* /*request*/, ::goproxy::AddedNodesCount* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetNodes() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::goproxy::Null, ::goproxy::Nodes>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::goproxy::Null* request, ::goproxy::Nodes* response) { return this->GetNodes(context, request, response); }));}
    void SetMessageAllocatorFor_GetNodes(
        ::grpc::MessageAllocator< ::goproxy::Null, ::goproxy::Nodes>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::goproxy::Null, ::goproxy::Nodes>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::goproxy::Null* /*request*/, ::goproxy::Nodes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNodes(
      ::grpc::CallbackServerContext* /*context*/, const ::goproxy::Null* /*request*/, ::goproxy::Nodes* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AddNode<WithCallbackMethod_AddSubscription<WithCallbackMethod_FetchSubscriptionNodes<WithCallbackMethod_GetNodes<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AddNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddNode() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AddNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddNode(::grpc::ServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::AddedNodesCount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AddSubscription : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddSubscription() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AddSubscription() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddSubscription(::grpc::ServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::SubscriptionId* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FetchSubscriptionNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FetchSubscriptionNodes() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_FetchSubscriptionNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchSubscriptionNodes(::grpc::ServerContext* /*context*/, const ::goproxy::SubscriptionId* /*request*/, ::goproxy::AddedNodesCount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetNodes() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::goproxy::Null* /*request*/, ::goproxy::Nodes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddNode() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AddNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddNode(::grpc::ServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::AddedNodesCount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddNode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddSubscription : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddSubscription() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_AddSubscription() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddSubscription(::grpc::ServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::SubscriptionId* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddSubscription(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FetchSubscriptionNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FetchSubscriptionNodes() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_FetchSubscriptionNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchSubscriptionNodes(::grpc::ServerContext* /*context*/, const ::goproxy::SubscriptionId* /*request*/, ::goproxy::AddedNodesCount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchSubscriptionNodes(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetNodes() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::goproxy::Null* /*request*/, ::goproxy::Nodes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNodes(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddNode() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddNode(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddNode(::grpc::ServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::AddedNodesCount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddNode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddSubscription : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddSubscription() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddSubscription(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddSubscription() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddSubscription(::grpc::ServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::SubscriptionId* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddSubscription(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FetchSubscriptionNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FetchSubscriptionNodes() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FetchSubscriptionNodes(context, request, response); }));
    }
    ~WithRawCallbackMethod_FetchSubscriptionNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchSubscriptionNodes(::grpc::ServerContext* /*context*/, const ::goproxy::SubscriptionId* /*request*/, ::goproxy::AddedNodesCount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FetchSubscriptionNodes(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetNodes() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetNodes(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::goproxy::Null* /*request*/, ::goproxy::Nodes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNodes(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddNode() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::goproxy::Url, ::goproxy::AddedNodesCount>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::goproxy::Url, ::goproxy::AddedNodesCount>* streamer) {
                       return this->StreamedAddNode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddNode(::grpc::ServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::AddedNodesCount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddNode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::goproxy::Url,::goproxy::AddedNodesCount>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddSubscription : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddSubscription() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::goproxy::Url, ::goproxy::SubscriptionId>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::goproxy::Url, ::goproxy::SubscriptionId>* streamer) {
                       return this->StreamedAddSubscription(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddSubscription() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddSubscription(::grpc::ServerContext* /*context*/, const ::goproxy::Url* /*request*/, ::goproxy::SubscriptionId* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddSubscription(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::goproxy::Url,::goproxy::SubscriptionId>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FetchSubscriptionNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FetchSubscriptionNodes() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::goproxy::SubscriptionId, ::goproxy::AddedNodesCount>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::goproxy::SubscriptionId, ::goproxy::AddedNodesCount>* streamer) {
                       return this->StreamedFetchSubscriptionNodes(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FetchSubscriptionNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FetchSubscriptionNodes(::grpc::ServerContext* /*context*/, const ::goproxy::SubscriptionId* /*request*/, ::goproxy::AddedNodesCount* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFetchSubscriptionNodes(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::goproxy::SubscriptionId,::goproxy::AddedNodesCount>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetNodes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetNodes() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::goproxy::Null, ::goproxy::Nodes>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::goproxy::Null, ::goproxy::Nodes>* streamer) {
                       return this->StreamedGetNodes(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetNodes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetNodes(::grpc::ServerContext* /*context*/, const ::goproxy::Null* /*request*/, ::goproxy::Nodes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetNodes(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::goproxy::Null,::goproxy::Nodes>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AddNode<WithStreamedUnaryMethod_AddSubscription<WithStreamedUnaryMethod_FetchSubscriptionNodes<WithStreamedUnaryMethod_GetNodes<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AddNode<WithStreamedUnaryMethod_AddSubscription<WithStreamedUnaryMethod_FetchSubscriptionNodes<WithStreamedUnaryMethod_GetNodes<Service > > > > StreamedService;
};

}  // namespace goproxy


#endif  // GRPC_proxy_2eproto__INCLUDED
