// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proxy.proto

#include "proxy.pb.h"
#include "proxy.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace goproxy {

static const char* NodeService_method_names[] = {
  "/goproxy.NodeService/AddNode",
  "/goproxy.NodeService/AddSubscription",
  "/goproxy.NodeService/FetchSubscriptionNodes",
  "/goproxy.NodeService/GetNodes",
};

std::unique_ptr< NodeService::Stub> NodeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NodeService::Stub> stub(new NodeService::Stub(channel, options));
  return stub;
}

NodeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AddNode_(NodeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddSubscription_(NodeService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FetchSubscriptionNodes_(NodeService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNodes_(NodeService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NodeService::Stub::AddNode(::grpc::ClientContext* context, const ::goproxy::Url& request, ::goproxy::AddedNodesCount* response) {
  return ::grpc::internal::BlockingUnaryCall< ::goproxy::Url, ::goproxy::AddedNodesCount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddNode_, context, request, response);
}

void NodeService::Stub::async::AddNode(::grpc::ClientContext* context, const ::goproxy::Url* request, ::goproxy::AddedNodesCount* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::goproxy::Url, ::goproxy::AddedNodesCount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddNode_, context, request, response, std::move(f));
}

void NodeService::Stub::async::AddNode(::grpc::ClientContext* context, const ::goproxy::Url* request, ::goproxy::AddedNodesCount* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddNode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>* NodeService::Stub::PrepareAsyncAddNodeRaw(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::goproxy::AddedNodesCount, ::goproxy::Url, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddNode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>* NodeService::Stub::AsyncAddNodeRaw(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddNodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NodeService::Stub::AddSubscription(::grpc::ClientContext* context, const ::goproxy::Url& request, ::goproxy::SubscriptionId* response) {
  return ::grpc::internal::BlockingUnaryCall< ::goproxy::Url, ::goproxy::SubscriptionId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddSubscription_, context, request, response);
}

void NodeService::Stub::async::AddSubscription(::grpc::ClientContext* context, const ::goproxy::Url* request, ::goproxy::SubscriptionId* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::goproxy::Url, ::goproxy::SubscriptionId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddSubscription_, context, request, response, std::move(f));
}

void NodeService::Stub::async::AddSubscription(::grpc::ClientContext* context, const ::goproxy::Url* request, ::goproxy::SubscriptionId* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddSubscription_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::goproxy::SubscriptionId>* NodeService::Stub::PrepareAsyncAddSubscriptionRaw(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::goproxy::SubscriptionId, ::goproxy::Url, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddSubscription_, context, request);
}

::grpc::ClientAsyncResponseReader< ::goproxy::SubscriptionId>* NodeService::Stub::AsyncAddSubscriptionRaw(::grpc::ClientContext* context, const ::goproxy::Url& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddSubscriptionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NodeService::Stub::FetchSubscriptionNodes(::grpc::ClientContext* context, const ::goproxy::SubscriptionId& request, ::goproxy::AddedNodesCount* response) {
  return ::grpc::internal::BlockingUnaryCall< ::goproxy::SubscriptionId, ::goproxy::AddedNodesCount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FetchSubscriptionNodes_, context, request, response);
}

void NodeService::Stub::async::FetchSubscriptionNodes(::grpc::ClientContext* context, const ::goproxy::SubscriptionId* request, ::goproxy::AddedNodesCount* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::goproxy::SubscriptionId, ::goproxy::AddedNodesCount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FetchSubscriptionNodes_, context, request, response, std::move(f));
}

void NodeService::Stub::async::FetchSubscriptionNodes(::grpc::ClientContext* context, const ::goproxy::SubscriptionId* request, ::goproxy::AddedNodesCount* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FetchSubscriptionNodes_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>* NodeService::Stub::PrepareAsyncFetchSubscriptionNodesRaw(::grpc::ClientContext* context, const ::goproxy::SubscriptionId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::goproxy::AddedNodesCount, ::goproxy::SubscriptionId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FetchSubscriptionNodes_, context, request);
}

::grpc::ClientAsyncResponseReader< ::goproxy::AddedNodesCount>* NodeService::Stub::AsyncFetchSubscriptionNodesRaw(::grpc::ClientContext* context, const ::goproxy::SubscriptionId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFetchSubscriptionNodesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NodeService::Stub::GetNodes(::grpc::ClientContext* context, const ::goproxy::Null& request, ::goproxy::Nodes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::goproxy::Null, ::goproxy::Nodes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNodes_, context, request, response);
}

void NodeService::Stub::async::GetNodes(::grpc::ClientContext* context, const ::goproxy::Null* request, ::goproxy::Nodes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::goproxy::Null, ::goproxy::Nodes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodes_, context, request, response, std::move(f));
}

void NodeService::Stub::async::GetNodes(::grpc::ClientContext* context, const ::goproxy::Null* request, ::goproxy::Nodes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodes_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::goproxy::Nodes>* NodeService::Stub::PrepareAsyncGetNodesRaw(::grpc::ClientContext* context, const ::goproxy::Null& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::goproxy::Nodes, ::goproxy::Null, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNodes_, context, request);
}

::grpc::ClientAsyncResponseReader< ::goproxy::Nodes>* NodeService::Stub::AsyncGetNodesRaw(::grpc::ClientContext* context, const ::goproxy::Null& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNodesRaw(context, request, cq);
  result->StartCall();
  return result;
}

NodeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::goproxy::Url, ::goproxy::AddedNodesCount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::goproxy::Url* req,
             ::goproxy::AddedNodesCount* resp) {
               return service->AddNode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::goproxy::Url, ::goproxy::SubscriptionId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::goproxy::Url* req,
             ::goproxy::SubscriptionId* resp) {
               return service->AddSubscription(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::goproxy::SubscriptionId, ::goproxy::AddedNodesCount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::goproxy::SubscriptionId* req,
             ::goproxy::AddedNodesCount* resp) {
               return service->FetchSubscriptionNodes(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::goproxy::Null, ::goproxy::Nodes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::goproxy::Null* req,
             ::goproxy::Nodes* resp) {
               return service->GetNodes(ctx, req, resp);
             }, this)));
}

NodeService::Service::~Service() {
}

::grpc::Status NodeService::Service::AddNode(::grpc::ServerContext* context, const ::goproxy::Url* request, ::goproxy::AddedNodesCount* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::AddSubscription(::grpc::ServerContext* context, const ::goproxy::Url* request, ::goproxy::SubscriptionId* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::FetchSubscriptionNodes(::grpc::ServerContext* context, const ::goproxy::SubscriptionId* request, ::goproxy::AddedNodesCount* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::GetNodes(::grpc::ServerContext* context, const ::goproxy::Null* request, ::goproxy::Nodes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace goproxy

