# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proxy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproxy.proto\x12\x07goproxy\"}\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\x05\x12\x11\n\ttransport\x18\x06 \x01(\t\x12\x0b\n\x03tls\x18\x07 \x01(\t\x12\x0e\n\x06source\x18\x08 \x01(\t\"%\n\x05Nodes\x12\x1c\n\x05nodes\x18\x01 \x03(\x0b\x32\r.goproxy.Node\"\x12\n\x03Url\x12\x0b\n\x03url\x18\x01 \x01(\t\"2\n\x0f\x41\x64\x64\x65\x64NodesCount\x12\r\n\x05\x61\x64\x64\x65\x64\x18\x01 \x01(\x03\x12\x10\n\x08received\x18\x02 \x01(\x03\"\x1c\n\x0eSubscriptionId\x12\n\n\x02id\x18\x01 \x01(\t\"\x06\n\x04Null2\xf2\x01\n\x0bNodeService\x12\x31\n\x07\x41\x64\x64Node\x12\x0c.goproxy.Url\x1a\x18.goproxy.AddedNodesCount\x12\x38\n\x0f\x41\x64\x64Subscription\x12\x0c.goproxy.Url\x1a\x17.goproxy.SubscriptionId\x12K\n\x16\x46\x65tchSubscriptionNodes\x12\x17.goproxy.SubscriptionId\x1a\x18.goproxy.AddedNodesCount\x12)\n\x08GetNodes\x12\r.goproxy.Null\x1a\x0e.goproxy.Nodesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODE']._serialized_start=24
  _globals['_NODE']._serialized_end=149
  _globals['_NODES']._serialized_start=151
  _globals['_NODES']._serialized_end=188
  _globals['_URL']._serialized_start=190
  _globals['_URL']._serialized_end=208
  _globals['_ADDEDNODESCOUNT']._serialized_start=210
  _globals['_ADDEDNODESCOUNT']._serialized_end=260
  _globals['_SUBSCRIPTIONID']._serialized_start=262
  _globals['_SUBSCRIPTIONID']._serialized_end=290
  _globals['_NULL']._serialized_start=292
  _globals['_NULL']._serialized_end=298
  _globals['_NODESERVICE']._serialized_start=301
  _globals['_NODESERVICE']._serialized_end=543
# @@protoc_insertion_point(module_scope)
