# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proxy_pb2 as proxy__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proxy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddNode = channel.unary_unary(
                '/goproxy.NodeService/AddNode',
                request_serializer=proxy__pb2.Url.SerializeToString,
                response_deserializer=proxy__pb2.AddedNodesCount.FromString,
                _registered_method=True)
        self.AddSubscription = channel.unary_unary(
                '/goproxy.NodeService/AddSubscription',
                request_serializer=proxy__pb2.Url.SerializeToString,
                response_deserializer=proxy__pb2.SubscriptionId.FromString,
                _registered_method=True)
        self.FetchSubscriptionNodes = channel.unary_unary(
                '/goproxy.NodeService/FetchSubscriptionNodes',
                request_serializer=proxy__pb2.SubscriptionId.SerializeToString,
                response_deserializer=proxy__pb2.AddedNodesCount.FromString,
                _registered_method=True)
        self.GetNodes = channel.unary_unary(
                '/goproxy.NodeService/GetNodes',
                request_serializer=proxy__pb2.Null.SerializeToString,
                response_deserializer=proxy__pb2.Nodes.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSubscription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchSubscriptionNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddNode': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNode,
                    request_deserializer=proxy__pb2.Url.FromString,
                    response_serializer=proxy__pb2.AddedNodesCount.SerializeToString,
            ),
            'AddSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSubscription,
                    request_deserializer=proxy__pb2.Url.FromString,
                    response_serializer=proxy__pb2.SubscriptionId.SerializeToString,
            ),
            'FetchSubscriptionNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchSubscriptionNodes,
                    request_deserializer=proxy__pb2.SubscriptionId.FromString,
                    response_serializer=proxy__pb2.AddedNodesCount.SerializeToString,
            ),
            'GetNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodes,
                    request_deserializer=proxy__pb2.Null.FromString,
                    response_serializer=proxy__pb2.Nodes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'goproxy.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('goproxy.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/goproxy.NodeService/AddNode',
            proxy__pb2.Url.SerializeToString,
            proxy__pb2.AddedNodesCount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/goproxy.NodeService/AddSubscription',
            proxy__pb2.Url.SerializeToString,
            proxy__pb2.SubscriptionId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchSubscriptionNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/goproxy.NodeService/FetchSubscriptionNodes',
            proxy__pb2.SubscriptionId.SerializeToString,
            proxy__pb2.AddedNodesCount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/goproxy.NodeService/GetNodes',
            proxy__pb2.Null.SerializeToString,
            proxy__pb2.Nodes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
